### ISSUE TITLE
Failed to execute postMessage warning after clearing a microfrontend outlet and immediately sending an intent

### ISSUE THREAD

**Issue by k-genov** [SchweizerischeBundesbahnen/scion-microfrontend-platform#168]
The reset logic in our application is as follows:

Shell clears all outlets of the connected microfrontends (i.e. page reload)
Send intent to the microfrontend activators so that they can perform some other reset logic (i.e. clear session storage)
Pseudo code
combineLatest(this.outletRouter.navigate(null, {outlet: PRIMARY_OUTLET}), /* ... */)
    .pipe(
      switchMap(() => this.intentClient.publish({type: 'reset'})),
      take(1)
    )
    .subscribe(/* ... */)
It seems that the intent is also received from the outlet being cleared, which does not have an active subscription and this also leads to following error in the console:

scion-microfrontend-platform.mjs:2657 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://localhost:4200/') does not match the recipient window's origin ('http://localhost:4000/').

localhost:4000 is host and localhost:4200 is the microfrontend being reset.

According to @danielwiehl related to #124

**Comment by danielwiehl** [comment]
Thank you for reporting the issue. The problem will probably be fixed with issue https://github.com/SchweizerischeBundesbahnen/scion-microfrontend-platform/issues/124. Nevertheless, we should investigate the issue and fix it separately.
