### ISSUE TITLE
Provide API to listen to the progress of the startup process

### ISSUE THREAD

**Issue by danielwiehl** [SchweizerischeBundesbahnen/scion-microfrontend-platform#18]
## Is your feature request related to a problem? Please describe.
The platform startup may take some time, especially when waiting for activators to signal readiness. The platform should provide an API to listen to the progress of the startup process so that the progress can be visualized with a progress bar or similar.

## Describe the solution you'd like
The API should continuously report the current status of the startup process. It should not be limited to the progress of the activators but should apply generally to the entire startup progress of the platform.

**Comment by efux** [comment]
I think this is related to #6. It would also be great, if we can configure a timeout when waiting for their activators and the developer can then decide, what should happen if a Micro Frontend does not start in time (either continue or block the application).
