### ISSUE TITLE
Testing URL

### ISSUE THREAD

**Issue by Nadynho** [SchweizerischeBundesbahnen/scion-microfrontend-platform#2]
Hello,

Well, first of all this is not a complaint, it's more like a question. 

In the past, you had a URL where we could demonstrate the capabilities of the framework that you are building, this was the URL: https://scion-microfrontend-platform-app-1.now.sh/#/testing-app/browser-outlets;count=3.

Do you still have such testing URL? Can you please share it somewhere in the documentation or point me to a direction?

And I'll end with the assumption that you guys have been safe during this period! :)

Thanks,
Bogdan.

**Comment by danielwiehl** [comment]
Hi Bogdan

We still have the test application you mentioned, but publish it under a versioned URL. The application is crucial for our automated regression testing of the SCION Microfrontend Platform :-)

Starting with version `1.0.0-beta.1`, the URL is as follows:
https://scion-microfrontend-platform-testing-app1-v1-0-0-beta-1.now.sh

For the next version `1.0.0-beta.2`, the URL will be as follows: :
https://scion-microfrontend-platform-testing-app1-v1-0-0-beta-2.now.sh

And for the major release `1.0.0`, the URL will be as follows:
https://scion-microfrontend-platform-testing-app1-v1-0-0.now.sh

**The test application will still be available for old versions.**

In our [Developer's Guide](https://scion-microfrontend-platform-developer-guide.now.sh/), chapter [4.6 Exploring SCION Microfrontend Platform](https://scion-microfrontend-platform-developer-guide.now.sh/#chapter:explore-scion-microfrontend-platform), we have linked to the test application accordingly.

If you have further questions, please do not hesitate to ask them.
