### ISSUE TITLE
Make sci-router-outlet CSP nonce compatible.

### ISSUE THREAD

**Issue by valentin-kennke** [SchweizerischeBundesbahnen/scion-microfrontend-platform#287]
## Is your feature request related to a problem? Please describe.
Our Angular application implements Content Security Policy (CSP) using ngCspNonce (as described in https://angular.dev/best-practices/security#content-security-policy). However, this doesn't affect the inline styles [[1](https://github.com/SchweizerischeBundesbahnen/scion-microfrontend-platform/blob/da93cb740eab619fa2a8358d103f9e189d879705/projects/scion/microfrontend-platform/src/lib/client/router-outlet/router-outlet.element.ts#L29)] within the shadow DOM of sci-router-outlet. As a result, we're forced to use the unsafe-inline directive in our CSP, which compromises our application's security posture.

## Describe the solution you'd like
We propose modifying the Web Component to support CSP nonces for its styles. This could be achieved by:

1. Accepting a data-nonce attribute on the sci-router-outlet Web Component.
2. The inline styles should not be part of the HTML_TEMPLATE but should be added to the shadow DOM in the constructor of SciRouterOutletElement.
3. Using the nonce when creating the <style> element within the shadow DOM.

Here's a basic implementation example:

```typescript
this._shadowRoot = this.attachShadow({mode: 'open'});
const nonce = this.getAttribute('data-nonce');
const style = document.createElement('style');
    
if (nonce) {
   style.setAttribute('nonce', nonce);
}

style.textContent = 
   /* the inline-style as in [1] */
;
    
this._shadowRoot.appendChild(style);
```

This approach would allow us to use your Web Component without compromising our CSP settings.

[1] https://github.com/SchweizerischeBundesbahnen/scion-microfrontend-platform/blob/da93cb740eab619fa2a8358d103f9e189d879705/projects/scion/microfrontend-platform/src/lib/client/router-outlet/router-outlet.element.ts#L29

**Comment by danielwiehl** [comment]
Thank you, @valentin-kennke , for reporting and analyzing the problem.

I think the nonce should be part of the global configuration, not set per `sci-router-outlet`, as the platform also requires the nonce to load activator microfrontends.

**Comment by danielwiehl** [comment]
An alternative would be using a constructable stylesheet, which does not require a nonce.
