### ISSUE TITLE
Write Security Whitepaper

### ISSUE THREAD

**Issue by simoneggler** [SchweizerischeBundesbahnen/scion-microfrontend-platform#5]
## Is your feature request related to a problem? Please describe.
Is it secure to use the SCION Microfrontend Platform? The host application integrates applications from different origins by sending messages via the browsers messaging infrastructure. Can these messages be intercepted? Are there other potential vulnerabilities to consider?

## Describe the solution you'd like
Write a document detailing how the SCION Microfrontend Platform secures itself and its hosted applications.

**Comment by danielwiehl** [comment]
Hi @marchof and @simoneggler 

We have added the following chapter on security to the [Developer Guide](https://scion-microfrontend-platform-developer-guide.now.sh) of the SCION Microfrontend Platform: https://scion-microfrontend-platform-developer-guide.now.sh/#chapter:security.

Could you please review it? Is this explanation sufficient, or are you missing something? We would like you to make changes or additions directly in the guide and send us a pull request.
