### ISSUE TITLE
Extract the platform config loading logic from ManifestCollector in a separate bean

### ISSUE THREAD

**Issue by k-genov** [SchweizerischeBundesbahnen/scion-microfrontend-platform#84]
## Is your feature request related to a problem? Please describe.
Currentrly the ManifestCollector is responsible for:
- loading the platform config 
- fetching and registering the manifests of the micro apps
https://github.com/SchweizerischeBundesbahnen/scion-microfrontend-platform/blob/master/projects/scion/microfrontend-platform/src/lib/host/manifest-collector.ts#L36

## Describe the solution you'd like
Flowing the separation of concerns principle it would be better to split the bean and extract the platform config loading logic into a separate bean e.g. PlatformConfigLoader

## Additional context
Check the run level configuration. The ManifestCollector uses runlevel 0, the PlatformConfigLoader should be loaded before the ManifestCollector .

**Comment by danielwiehl** [comment]
The API for loading the platform config asynchronously has been removed in issue #96. Instead, the application should load the configuration before starting the platform and pass it to `MicrofrontendPlatform#startHost`. 

@k-genov Please have a look at PR #105 and let me know if we can close this issue as resolved.
