### ISSUE TITLE
Increase throughput of message broker

### ISSUE THREAD

**Issue by adriansacchi** [SchweizerischeBundesbahnen/scion-microfrontend-platform#90]
## Is your feature request related to a problem? Please describe.
When there is a lot load on the message bus, some intents get rejected with this error:

`[MessageDispatchError] Broker did not report message delivery state within the 10000ms timeout.`

The respective timeout could be increased in 'MicroApplicationConfig' but this still leaves us with a laggy application.

Reproducer (tested with Google Chrome Version 92.0.4515.131): 
```
capability: 
    {
      "type": "to-uppercase",
      "requiredParams": [
        "payload"
      ],
      "description": "Converts the provided payload to uppercase."
    },

intent-handler:
    this._intentClient.onIntent({type: 'to-uppercase'}, ({intent})=> {
      return of((intent.params.get('payload') as string).toUpperCase());
    });

invocation:
    for (let i = 0; i < 1000; i++) {
      this._intentClient.request$({type: 'to-uppercase', params: new Map().set('payload', 'lorem ipsum')})
        .subscribe((message) => console.log('>> toUpper: ', message.body));
    }
```

## Describe the solution you'd like
Validate the following hypothesis: "The problem is the number of single messages but not the combined size of all messages."

Try to increase throughput by implementing something like this: 
- When publishing intents detect whether there currently is a high-load situation.
  - If so: bundle intents (and possibly also replies) for publishing
  - If not: do not bundle intents (avoid additional delay)

**Comment by danielwiehl** [comment]
Thank you @adriansacchi for filing this issue.  It may be related to issue #14, which we will fix soon.
